# Generated by Django 5.0 on 2024-01-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrow_after_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
